# Generated by Django 5.0.6 on 2024-08-02 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calorias', models.FloatField(default=0)),
                ('proteinas', models.FloatField(default=0)),
                ('carbohidratos', models.FloatField(default=0)),
                ('grasas', models.FloatField(default=0)),
                ('cantidad_gramos', models.FloatField(default=0)),
                ('cantidad_unidades', models.FloatField(default=0)),
                ('unidad', models.CharField(default='Rebanadas/porciones/Tazas', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='alimentos/')),
                ('nutrientes', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
                ('porcentaje_calorias', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('edad', models.IntegerField(default=18)),
                ('peso', models.FloatField(default=50)),
                ('altura', models.FloatField(default=150)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('nivel_actividad', models.FloatField(choices=[(1.2, 'Sedentario'), (1.375, 'Ligero'), (1.55, 'Moderado'), (1.725, 'Activo'), (1.9, 'Muy activo')], default=1.2)),
                ('cuello', models.FloatField(default=30)),
                ('cintura', models.FloatField(default=60)),
                ('caderas', models.FloatField(default=90)),
                ('objetivo_entrenamiento', models.CharField(choices=[('Aumentar masa muscular', 'Aumentar masa muscular'), ('Mantener peso', 'Mantener peso'), ('Reducir porcentaje de grasa', 'Reducir porcentaje de grasa')], default='Mantener peso', max_length=30)),
                ('objetivo_peso', models.FloatField(blank=True, choices=[(1.1, '0.5 kg/semana'), (1.15, '3 kg/semana'), (1.2, '5 kg/semana')], null=True)),
                ('macros_proteina', models.FloatField(default=21)),
                ('macros_carbohidratos', models.FloatField(default=50)),
                ('macros_grasas', models.FloatField(default=29)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Opcion sin nombre', max_length=100)),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_menu', to='gestor.comida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AlimentoEnOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('cantidad_unidades', models.FloatField(default=0)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.alimento')),
                ('opcion_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_en_opcion', to='gestor.opcionmenu')),
            ],
        ),
        migrations.AddField(
            model_name='comida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.usuario'),
        ),
    ]
